name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          template: terminal
          base: header, activity, repositories
          
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_details: percentage              # Additionally display total bytes size and percentage
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used          # Display most used and recently used languages stats
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          commits_authoring: lowlighter@users.noreply.github.com  
          repositories_affiliations: owner, collaborator
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year
          plugin_lines: yes
          config_timezone: Europe/Istanbul # Set timezone
